# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161215_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
