# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='side',
            old_name='discription',
            new_name='side_discription',
        ),
        migrations.RenameField(
            model_name='side',
            old_name='image',
            new_name='side_image',
        ),
        migrations.RenameField(
            model_name='side',
            old_name='title',
            new_name='side_title',
        ),
    ]
