# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20161220_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=250)),
                ('rating', models.IntegerField(max_length=10)),
            ],
        ),
    ]
