# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort_discription',
            field=models.TextField(default='SOME discription'),
        ),
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='side',
            name='side_discription',
            field=models.TextField(),
        ),
    ]
