# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20161227_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_bottam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.CharField(max_length=250)),
                ('news_title', models.CharField(max_length=205)),
                ('news_sort_discriptions', models.TextField()),
                ('news_discriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News_category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.CharField(max_length=250)),
                ('news_title', models.CharField(max_length=205)),
                ('news_discriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News_category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.CharField(max_length=250)),
                ('news_title', models.CharField(max_length=205)),
                ('news_discriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News_middel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.CharField(max_length=250)),
                ('news_title', models.CharField(max_length=205)),
                ('news_sort_discriptions', models.TextField()),
                ('news_discriptions', models.TextField()),
            ],
        ),
    ]
