# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_bottam_news_category1_news_category2_news_middel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_bottam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_image', models.CharField(max_length=250)),
                ('game_title', models.CharField(max_length=205)),
                ('game_sort_discriptions', models.TextField()),
                ('game_discriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_image', models.CharField(max_length=250)),
                ('game_title', models.CharField(max_length=205)),
                ('game_discriptions', models.TextField()),
            ],
        ),
    ]
