# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_game_bottam_game_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_image', models.CharField(max_length=250)),
                ('review_title', models.CharField(max_length=250)),
                ('review_rating', models.FloatField(max_length=10)),
                ('review_review', models.CharField(max_length=250)),
                ('review_sort_discription', models.TextField()),
                ('review_discription', models.TextField()),
            ],
        ),
    ]
